source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
 platform :ios, '15.3.1'

target 'Testing_Lokalise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


end
